export const categories = [
  "Programming",
  "Design",
  "Business",
  "Marketing",
  "IT",
  "Data Science",
  "Personal Development",
  "Photography",
  "Music",
  "Health & Fitness",
  "Lifestyle",
  "Language",
  "Academics",
  "Test Prep",
];
